<h1>The view script delete.phtml</h1>

<?php
// module/Album/view/empregado/empregado/delete.phtml:

$nome = 'Delete empregado';
$this->headTitle($nome);
?>
<h1><?php echo $this->escapeHtml($nome); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($empregado->nome); ?>' by
    '<?php echo $this->escapeHtml($empregado->telefone); ?>'?
    '<?php echo $this->escapeHtml($empregado->login); ?>'?
    '<?php echo $this->escapeHtml($empregado->senha); ?>'?
    '<?php echo $this->escapeHtml($empregado->loginp); ?>'?
    '<?php echo $this->escapeHtml($empregado->cargo); ?>'?
</p>
<?php
$url = $this->url('empregado', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $empregado->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>