<?php


$title = 'Empregado';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('empregado', array('action'=>'add'));?>">Add new empregado</a>
</p>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Login</th>
    <th>Senha</th>
    <th>Patrão</th>
    <th>Cargo</th>
    <th>Opções</th>
</tr>
<?php foreach ($empregados as $empregado) : ?>
<tr>
    <td><?php echo $this->escapeHtml($empregado->nome);?></td>
    <td><?php echo $this->escapeHtml($empregado->telefone);?></td>
    <td><?php echo $this->escapeHtml($empregado->login);?></td>
    <td><?php echo $this->escapeHtml($empregado->senha);?></td>
    <td><?php echo $this->escapeHtml($empregado->loginp);?></td>
    <td><?php echo $this->escapeHtml($empregado->cargo);?></td>
    <td>
        <a href="<?php echo $this->url('empregado',
            array('action'=>'edit', 'id' => $empregado->id));?>" class="btn btn-primary btn-mini edit-row">Edit</a>
        <a href="<?php echo $this->url('empregado',
            array('action'=>'delete', 'id' => $empregado->id));?>" class="btn btn-primary btn-mini edit-row">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>