<h1>The view script edit.phtml</h1>

<?php
// module/Album/view/patrao/patrao/edit.phtml:

$nome = 'Edit patrao';
$this->headTitle($nome);
?>
<h1><?php echo $this->escapeHtml($nome); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'patrao',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form)."</br>";
echo $this->formHidden($form->get('id'))."</br>";
echo $this->formRow($form->get('nome'))."</br>";
echo $this->formRow($form->get('telefone'))."</br>";
echo $this->formRow($form->get('senha'))."</br>";
echo $this->formSubmit($form->get('submit'))."</br>";
echo $this->formHidden($form->get('longitude'))."</br>";
echo $this->formHidden($form->get('latitude'))."</br>";
echo $this->formHidden($form->get('login'))."</br>";
echo $this->form()->closeTag();