<?php


$title = 'Patrão';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('patrao', array('action'=>'add'));?>">Add new patrao</a>
</p>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Login</th>
    <th>Senha</th>
    <th>Long</th>
    <th>Lat</th>
    <th>Opções</th>
</tr>
<?php foreach ($patraos as $patrao) : ?>
<tr>
    <td><?php echo $this->escapeHtml($patrao->nome);?></td>
    <td><?php echo $this->escapeHtml($patrao->telefone);?></td>
    <td><?php echo $this->escapeHtml($patrao->login);?></td>
    <td><?php echo $this->escapeHtml($patrao->senha);?></td>
    <td><?php echo $this->escapeHtml($patrao->longitude);?></td>
    <td><?php echo $this->escapeHtml($patrao->latitude);?></td>
    <td>
        <a href="<?php echo $this->url('patrao',
            array('action'=>'edit', 'id' => $patrao->id));?>" class="btn btn-primary btn-mini edit-row">Edit</a>
        <a href="<?php echo $this->url('patrao',
            array('action'=>'delete', 'id' => $patrao->id));?>" class="btn btn-primary btn-mini edit-row">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>