<?php


$title = 'Patrao (application)';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('patrao', array('action'=>'add'));?>">Add new patrao</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($patraos as $patrao) : ?>
<tr>
    <td><?php echo $this->escapeHtml($patrao->nome);?></td>
    <td><?php echo $this->escapeHtml($patrao->telefone);?></td>
    <td>
        <a href="<?php echo $this->url('patrao',
            array('action'=>'edit', 'id' => $patrao->id));?>">Edit</a>
        <a href="<?php echo $this->url('patrao',
            array('action'=>'delete', 'id' => $patrao->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>