<?php

$title = 'Ponto Digital';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="well">
    <form method="POST">
        <p>Login: <input name="login" type="text"></p>
        <p>Senha: <input name="senha" type="password"></p>
        <!-- <a class="btn btn-primary btn-mini edit-row" href="<?php echo $this->url('patrao');?>">Entrar</a> -->
         <a class="btn btn-primary btn-mini edit-row" href="<?php echo $this->url('painel', array('action'=>'painel'));?>">Entrar</a>
    </form>
</div>